### ISSUE TITLE
Breaking facebook post menu

### ISSUE THREAD

**Issue by levicki** [k2jp/abp-japanese-filters#20]
According to your support policy you will most certainly ignore this report, but I will still report the issue so that others may lose less time to figure out what is wrong with their Facebook when using this list.

This filter list is breaking facebook post menu (the little down arrow on the top right corner of each post which is used to access options to hide post, unfollow poster, etc):

With ABP JPN list active:
![broken](https://cloud.githubusercontent.com/assets/16415478/17030982/4a0c402e-4f72-11e6-9a82-4d25de4ba565.png)

With ABP JPN list inactive:
![working](https://cloud.githubusercontent.com/assets/16415478/17030983/4a0dba26-4f72-11e6-8089-8887a084dc09.png)

I use this list when visiting Japanese sites so I can definitely live without it, but it would be nice if you loked into it and fixed it.

**Comment by k2jp** [comment]
[Wrong subscription] No support available for you
You are violating the Support Policy.
　https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy

**Comment by item4** [comment]
I also encountered this problem. macOS 10.12.1 + firefox developer edition + ublock origin + ABP JPN

**Comment by k2jp** [comment]
### Support Policy
- https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy

**Comment by toshiya44** [comment]
Try this

```
! unblocks facebook options menu
@@||www.facebook.com/*/options_menu/?button*$xmlhttprequest,first-party
@@||www.facebook.com/ajax/groups/mall/mall_post_menu.php$xmlhttprequest,first-party
```

**Comment by levicki** [comment]
@k2jp 

We all understand your support policy and we respect it, but could you please consider making an exception and including the above provided exclusion filters in your list?

The author of uBlock Origin has been forced to consider removing your list completely from uBlock Origin subscription configuration page since people have started complaining to him about this issue and he is unable to fix it because you are the list owner.

I am sure there are a lot of current and future Japanese uBlock Origin users who would be at a loss if your list was no longer offered on the uBlock Origin subscription configuration page.

**Comment by k2jp** [comment]
### More open-source way
- @toshiya44 can create/publish complementary subscription for ABP Japanese Filters to fix Facebook problems. Write a blog and share it. This doesn't break [Support Policy](https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy).

### Don't forget EasyList
- EasyList supports Facebook, right?

### Remember the official name
- ABP Japanese filters (ONLY FOR **Japanese** and **experienced** users: READ [Support Policy](https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy))

#### Some consideration
1. Include filters from guest contributors.
2. The filters will get obsolete sooner or later.
3. Who to maintain the filters after guest contributors are gone? Who to be responsible for that? New users will continue to create the similar issues again and ask me why filters on Facebook is not updated, repeatedly.

**Comment by levicki** [comment]
@k2jp 
Thanks for the reply. Allow me to answer your suggestions:

**More open-source way**
In my opinion collaboration is more open-source than forking.

**Don't forget EasyList**
Everyone using AdBlock or uBlock Origin is already using EasyList and one (or more) of the regional lists (I use CHN, RUS, JPN). I am not aware of Japanese EasyList, could you be more specific please?

**Remember the official name**
How do you expect putting a name on something you make available to everyone with Internet access will stop non-Japanese people with interest in Japan culture from using it? If you really do not want outsiders to use your list then you should ask the ad blocking plugin authors not to include it on their list subscription configuration page and block all non-Japanese IPs from downloading the list.

**Some considerations**
How about just changing the offending line to `https:*_ad_$domain=~facebook.com` then? That will fix the problem and eliminate the need for you to test or maintain the filter. I see that you already have some domain exclusions in there.

Once again sorry to bother you, if you are certain that you don't want to collaborate we will look into other previously discussed ways of solving the problem.

**Comment by k2jp** [comment]
#### A few facts
- There is no official EasyList family for Japanese, but are [a few independent alternative subscriptions by other Japanese authors for Japanese web sites](https://github.com/k2jp/abp-japanese-filters/wiki/OtherJapaneseFilters).
- Subscription authors listed on the [Adblock Plus sbscription page](https://adblockplus.org/en/subscriptions) receive very useful Issue Reports like [this](http://k2jp.hatenablog.com/) submitted by Adblock Plus users. That's why my subscription is on the list. Basically, uBlock Origin, AdBlock or other blocker authors just copy the list from adblockplus.org.
- My subscription is introduced as **Specialization: 日本語** on the [Subscription Page on the adblockplus.org](https://adblockplus.org/en/subscriptions). **日本語** means Japanese language, not culture or something else.

#### Based on the [Support Policy](https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy)
- I don't have to answer questions from uses who do not meet the [Support Policy](https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy) requirement.

@levicki 
Your opinion is different from mine and I don't have enough time to answer further questions.
FYI: If you just want to avoid false positives by too generic filters, try the options like **genericblock**. This option disable filters without domain restriction.
@@||facebook.com^$genericblock

**Comment by k2jp** [comment]
@toshiya44 
FYI: 
**~third-party** has better compatibility compared with **first-party**.

**Comment by levicki** [comment]
@k2jp 

One last thing -- I am aware that 日本語 means Japanese Language and when I mentioned "people with interest in Japan culture" I meant "people who are interested in visiting Japanese sites and learning things about Japan and its culture directly from the source (without seeing ads)". Maybe I should have spelled it out the first time around to avoid misunderstanding.

Thank you for your valuable time, and once again sorry for disturbing you.
