### ISSUE TITLE
Gmail broken and triggers thousands of hits/minute

### ISSUE THREAD

**Issue by dkaksl** [k2jp/abp-japanese-filters#32]
![jesus-christ-wtf-adblock](https://cloud.githubusercontent.com/assets/8690282/23109326/9030afb8-f75b-11e6-8e3e-5fe9ceb10e37.gif)

**Comment by toshiya44** [comment]
Try checking which filters are getting activated. I don't have this issue.

**Comment by dkaksl** [comment]
@toshiya44 `|https:*-ad-`

It matches an URL of the following format:

```
https://mail.google.com/mail/u/0/?ui=2&view=ss&mset=main&ver=<VER>&am=<LONG RANDOM? STRING THAT CONTAINS '-Ad-'>&fri
```

**Comment by toshiya44** [comment]
Yeah, I remember I had that issue but with a different filter list. I use,
```@@||mail.google.com/mail/u/$xmlhttprequest,domain=mail.google.com```

Might be worth it to ask easylist people to add it, since it's relevant to everyone.

**Comment by k2jp** [comment]
#### [Not reproducible]
* My Gmail requests do not match the `|https:*-ad-` filter.
* My Gmail does not request URLs including `*//mail.google.com/mail/u/*`
* My URL is slightly defferent form yours, probably because of multiple/single user names.
  * Yours: `https://mail.google.com/mail/ca/u/0/#inbox`
  * Mine: `https://mail.google.com/mail/#inbox`

#### Support Policy
- https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy

**Comment by dkaksl** [comment]
@k2jp I'm pretty sure you not reproducing the issue is luck. AFAIK the string that goes in the `am` parameter is random.

No idea why there's a `/ca/` in my URLs though.

**Comment by k2jp** [comment]
Expired
