### ISSUE TITLE
JPN filter blocks common English keywords & pages

### ISSUE THREAD

**Issue by methuzla** [k2jp/abp-japanese-filters#35]
Using the JPN filter in UK, I often find that 'normal' traffic in English  is too aggressively blocked.
For example ://offer.$document may well block a legitimate link.

What I hope for from a filter is for it to block intrusive advertising (specifically regional items), not to block normal parts of commercial sites.  I elected to use this JPN filter to avoid specifically Japanese nuisances, not to interfere  with normal English traffic. 
In fact, I don't understand why this list is blocking on English keywords, perhaps someone can explain?

Can anything be done to improve the tolerance of the main JPN list, or else to split off a separate list relevant to Japanese only?

**Comment by k2jp** [comment]
#### Misunderstanding?
ABP Japanese Filters is an __independent third-party__ subscription.
- __independent__ means that ABP Japanese Filters does not require an EasyList family.
- __third-party__ means that ABP Japanese Filters does not belong to an EasyList family.

#### Support Policy
Because of poor work force, support is limited.
 - https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy

#### Wrong subscription?
Find other subscription.
 - https://filterlists.com/
 - https://adblockplus.org/en/subscriptions

**Comment by methuzla** [comment]
はい。
ありがとうございました。
しつれいしました。
