### ISSUE TITLE
wrongly blocked google result for stackoverflow

### ISSUE THREAD

**Issue by NewUserHa** [k2jp/abp-japanese-filters#47]
the href of the result is:
`https://meta.stackexchange.com/questions/10372/is-stackoverflow-com-written-in-ruby-on-rails?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa`
it's the best result, so it's blocked wrongly

**Comment by lae** [comment]
For this particular issue, you might consider https://addons.mozilla.org/ja/firefox/addon/au-revoir-utm/. utm_* are tracking parameters.

**Comment by NewUserHa** [comment]
I mean this rule files blocked the right link. would you update the rule?

**Comment by lae** [comment]
I'm not the maintainer, I'm just passing by.

**Comment by cryptogun** [comment]
Same here. It says this line `_campaign=$document` is to blame.
`utm_` and `_campaign` are too ambiguous.
What *easylist* do is to append specific URL before these two keywords.

**Comment by k2jp** [comment]
I'm sorry to respond too late.

ABP Japanese Filters is independent subscription. In other words, it does not belong to the EasyList family.

`_campaign=$document` is useful to block AD redirection as I left comment when commit.

* https://github.com/k2jp/abp-japanese-filters/commit/1da7e0f78f4925469ef29fe6d78b69e36016ba33
* https://github.com/k2jp/abp-japanese-filters/commit/5e6c63340a6dddbf31e52c881f5a6aaaa2c3950a
* https://github.com/k2jp/abp-japanese-filters/commit/b55136a5ea6e82c8f21b435f86d0a00301f893d5

You should not follow the links including `&utm_campaign=` because the URL works without `&utm_campaign=`.
As lae mentioned, you can clean up URLs in advance. Why not follow clean links.

Remember the [Support Policy](https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy).
You can find other subscription...
* https://adblockplus.org/en/subscriptions
* https://filterlists.com/

**Comment by NewUserHa** [comment]
the link including `&utm_campaign=` is the **best and top one** google search result and there's **only one** in the search result page.
how can clean the link before blocker filter? and ads are also cleaned ?

**Comment by bogachenko** [comment]
@NewUserHa try this `@@||google.com/search^`

**Comment by k2jp** [comment]
[Deplicated] https://github.com/k2jp/abp-japanese-filters/issues/31

**Comment by k2jp** [comment]
Read my comment above carefully.
https://github.com/k2jp/abp-japanese-filters/issues/47#issuecomment-464370120

**Comment by k2jp** [comment]
[Duplicated] https://github.com/k2jp/abp-japanese-filters/issues/31
