### ISSUE TITLE
Unable to open Facebook post menu

### ISSUE THREAD

**Issue by rangilin** [k2jp/abp-japanese-filters#5]
I have trouble opening Facebook post menu if I apply your filter, the rule that blocks menu from log is `|https:*ad`, turn off your filter solve the problem.

For more detail, you can see the Issue I opened in uBlock.

https://github.com/gorhill/uBlock/issues/895

**Comment by k2jp** [comment]
The name of the filter subscription is "ABP Japanese filters (**ONLY for Japanese: see Support Policy**)".
You have to check the **Support Policy** in advance.
- https://code.google.com/p/adblock-plus-japanese-filter/wiki/Support_Policy

Facebook is not supported simply because I have never used it.

The FAQ page has already explained it but written only in Japanese, though. ;-p
- https://code.google.com/p/adblock-plus-japanese-filter/wiki/FAQ

If you want to disable |https:*ad, simply add a white-list filter.
- @@|https:*ad$domain=facebook.com
