### ISSUE TITLE
Badly implemented word filter

### ISSUE THREAD

**Issue by Fabian42** [k2jp/abp-japanese-filters#51]
Original text:
Blocked URL: Redirect of https://stackoverflow.com/users/story/integration/assessment?s=1
I can't publish the real URL, because it likely contains login data, but this one reproduces it as well: https://www.pluralsight.com/partners/stack-overflow/iq?promo=
And even this reproduces it: google.com/?promo
As well as: promo.com
Seems like everything containing the word "promo" is blocked.

New info: Apparently every URL containing "promo" or "click" is blocked. I can kind of understand why those words, but just blocking normal words completely is a really bad way of implementing a blocker. I suspect there are more words like these.

**Comment by k2jp** [comment]
I'm sorry to respond too late.

`promo` and `click` are typical word used for advertising or malvertising. that's why they are blocked.

If you want safer subscription, you can find at...
* https://adblockplus.org/en/subscriptions
* https://filterlists.com/

Remember the [Support Policy](https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy).

**Comment by Fabian42** [comment]
I'm not Japanese, so I guess it's fine to close this. But just blocking **everything** with "promo" in its URL is definitely not a good idea, as seen in the example I gave.
